 <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="{{lodspk.home}}">Global Hunger Index</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="{{lodspk.home}}">Home</a></li>
              <li><a href="{{lodspk.home}}classes">Classes</a></li>
              <li><a href="{{lodspk.home}}countries">Countries</a></li>
            </ul>
            <form class="navbar-search pull-left" action="">
              <input type="text" data-provide="typeahead" class="typeahead search-query span2" placeholder="Search a country"/>
            </form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
